drop table if exists course_group;
drop table if exists trainee_assessments;
drop table if exists trainee_attendance;
drop table if exists week_report;
drop table if exists Assessment;
drop table if exists Attendance;
drop table if exists Course;
drop table if exists hibernate_sequence;
drop table if exists Trainee;
drop table if exists Trainer;
drop table if exists User;
create table course_group (group_id integer not null auto_increment, course_id integer, current_week integer, end_date datetime, group_name varchar(255), start_date datetime, primary key (group_id)) type=MyISAM;
create table trainee_assessments (trainee_id integer not null, assessment_id integer not null, primary key (trainee_id, assessment_id)) type=MyISAM;
create table trainee_attendance (trainee_id integer not null, attendance_date date not null, attendance_id integer, day integer, week integer, primary key (trainee_id, attendance_date)) type=MyISAM;
create table week_report (report_id integer not null auto_increment, consultant_grade_trainee varchar(255), consultant_grade_trainer varchar(255), continue_trainee varchar(255), continue_trainer varchar(255), deadline datetime, most_recent_edit datetime, overall_grade_trainer varchar(255), start_trainee varchar(255), start_trainer varchar(255), stop_trainee varchar(255), stop_trainer varchar(255), technical_grade_trainee varchar(255), technical_grade_trainer varchar(255), trainee_consultant_grade_flag tinyint, trainee_continue_flag tinyint, trainee_id integer, trainee_start_flag tinyint, trainee_stop_flag tinyint, trainee_submitted_flag tinyint, trainee_technical_grade_flag tinyint, trainer_comments varchar(255), trainer_completed_flag tinyint, week_num integer, primary key (report_id)) type=MyISAM;
create table Assessment (assessment_id integer not null, test_id integer, primary key (assessment_id)) type=MyISAM;
create table Attendance (attendance_id integer not null, attendance_status varchar(255), primary key (attendance_id)) type=MyISAM;
create table Course (course_id integer not null, course_description varchar(255), course_name varchar(255), duration integer, primary key (course_id)) type=MyISAM;
create table hibernate_sequence (next_val bigint) type=MyISAM;
insert into hibernate_sequence values ( 1 );
create table Trainee (trainee_id integer not null auto_increment, first_name varchar(255), group_id integer, last_name varchar(255), username varchar(255), primary key (trainee_id)) type=MyISAM;
create table Trainer (trainer_id integer not null, first_name varchar(255), group_id integer, last_name varchar(255), username varchar(255), primary key (trainer_id)) type=MyISAM;
create table User (user_id integer not null auto_increment, password varchar(255), role varchar(255), username varchar(255), primary key (user_id)) type=MyISAM;
